#!/bin/sh
# Author: Mark D. Blackwell
# Date written: October 27, 2010
# Date last changed: March 29, 2011

# Find files matching a basename.
# Usage:
#   base <basename-expression>
# Example usage:
#   base \*.yml
#   base '*tag*'

find test app -name $1 -type f | sort
