#!/bin/sh
# Author: Mark D. Blackwell
# Change dates:
# mdb August 14, 2011 - create.
# mdb August 16, 2011 - use pull instead of fetch & merge FETCH_HEAD.
#
# Purpose: check GitHub for differences
# Usage:
#   git-fetch <directory path>

if cd $1; then pwd; git pull origin master; fi
