#!/bin/bash
# Author: Mark D. Blackwell
# Change dates:
# mdb August 14, 2011 create
# Purpose: check GitHub for differences
# Usage: get-fetch

cd ~/$1; git fetch origin master; git merge FETCH_HEAD
