#!/bin/bash
# Author: Mark D. Blackwell
# Change dates:
# mdb August 14, 2011 create
# Purpose: check GitHub for differences
# Usage:
#   git-fetch <directory path>

if cd $1; then pwd; git fetch origin master; git merge FETCH_HEAD; fi
