#!/bin/sh
# Author: Mark D. Blackwell
# Date written: October 29, 2010
# Date last changed: March 29, 2011

# Git files.
# Show all files new or modified since the last commit.
# Usage:
#   (In any directory under Git versioning.)
#   git-files
# Example usage:
#   nano `git-files`

git-diff --name-only HEAD | sort
