#!/bin/sh
# Author: Mark D. Blackwell
# Date written: November 5, 2010
# Date last changed: March 29, 2011

# Grep files.
# Show matching files, excluding certain directories.
# (Global regular expression print.)
# Usage:
#   grep-files <regexp>

grep --exclude=*\.sqlite3 \
--exclude-dir=\.git \
--exclude-dir=db \
--exclude-dir=javascripts \
--exclude-dir=log \
--exclude-dir=migrate \
--exclude-dir=out \
--exclude-dir=vendor \
--ignore-case \
--recursive --files-with-matches --regexp=$1 . | sort
# By hand:  grep -irle <regexp> <directory> | sort
