#!/bin/sh
# Author: Mark D. Blackwell
# Date written: December 21, 2010
# Date last changed: March 29, 2011

# Pathname.
# Find files matching a pathname shell expression.
# Usage:
#   pathn <pathname-shell-expression>
# Example usage:
#   pathn \*.yml
#   pathn '*tag*'
#   pathn '*/pic*'

find test app -path $1 -type f | sort
