#!/bin/sh
# Author: Mark D. Blackwell
# Date written: December 18, 2010
# Date last changed: March 29, 2011

# Recent.
# Find files changed in the last 24 hours.
# Usage:
#   recent
# Example usage:
#   recent

find app test -mtime 0 -type f | sort
