#!/bin/sh
# Author: Mark D. Blackwell
# Date written: October 21, 2010
# Date last changed: March 29, 2011

# Usage:
#   sm-install <Seamonkey version>

# For example:
#   sm-install 2.0.9

# One then can run Seamonkey by:
#   sm

# One can produce a Seamonkey download's md5 sum by the following example command:
#   openssl dgst -md5 ~/Downloads/seamonkey-2.0.9.tar.bz2

# This and Seamonkey should be run as a regular user (not root), in order that
# files in the ~/.mozilla profile be writable by Noscript and other plugins.

cd ~/seamonkey
tar -xjf ~/Downloads/seamonkey-$1.tar.bz2
mv seamonkey $1
cd ~/t
echo "~/seamonkey/$1/seamonkey" > sm
chmod u+x sm
