#!/bin/sh
# Author: Mark D. Blackwell
# Date written: December 18, 2010
# Date last changed: March 29, 2011

# Tree.
# List filenames in a given tree
# Usage:
#   tree <directory>
# Example usage:
#   trees pic\*

find $1 -type f | sort
